# Generated by Django 4.2.30 on 2026-08-28 05:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Budget',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.DateField(help_text='First day of the month for this budget')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=15)),
                ('amount_spent', models.DecimalField(decimal_places=2, default=0.0, max_digits=15)),
                ('status', models.CharField(choices=[('SAFE', 'Safe'), ('WARNING', 'Warning'), ('EXCEEDED', 'Exceeded')], default='SAFE', max_length=20)),
            ],
        ),
    ]
