# Generated by Django 4.2.30 on 2026-08-28 05:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notification_type', models.CharField(choices=[('BUDGET_WARNING', 'Budget Warning'), ('BUDGET_EXCEEDED', 'Budget Exceeded'), ('SAVINGS_PROGRESS', 'Savings Goal Progress'), ('LARGE_EXPENSE', 'Large Expense Warning'), ('RECURRING_REMINDER', 'Recurring Transaction Reminder'), ('SYSTEM', 'System Notification')], max_length=30)),
                ('message', models.TextField()),
                ('is_read', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
